/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Bookings */
        get: operations["list_my_bookings_api_v1_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_api_v1_bookings__booking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay Booking */
        post: operations["pay_booking_api_v1_bookings__booking_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking */
        post: operations["cancel_booking_api_v1_bookings__booking_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paystack Webhook */
        post: operations["paystack_webhook_api_v1_payments_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/salons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Salons */
        get: operations["list_salons_api_v1_salons_get"];
        put?: never;
        /** Create Salon */
        post: operations["create_salon_api_v1_salons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/salons/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Salons */
        get: operations["list_my_salons_api_v1_salons_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/salons/{salon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Salon */
        get: operations["get_salon_api_v1_salons__salon_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Salon */
        patch: operations["update_salon_api_v1_salons__salon_id__patch"];
        trace?: never;
    };
    "/api/v1/salons/{salon_id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_v1_salons__salon_id__services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_v1_salons__salon_id__services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/salons/{salon_id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Salon Bookings */
        get: operations["list_salon_bookings_api_v1_salons__salon_id__bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Service */
        delete: operations["delete_service_api_v1_services__service_id__delete"];
        options?: never;
        head?: never;
        /** Update Service */
        patch: operations["update_service_api_v1_services__service_id__patch"];
        trace?: never;
    };
    "/api/v1/salons/{salon_id}/stylists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stylists */
        get: operations["list_stylists_api_v1_salons__salon_id__stylists_get"];
        put?: never;
        /** Create Stylist */
        post: operations["create_stylist_api_v1_salons__salon_id__stylists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stylists/{stylist_id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Stylist Services */
        put: operations["set_stylist_services_api_v1_stylists__stylist_id__services_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stylists/{stylist_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Availability */
        get: operations["get_availability_api_v1_stylists__stylist_id__availability_get"];
        /** Set Availability */
        put: operations["set_availability_api_v1_stylists__stylist_id__availability_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stylists/{stylist_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slots */
        get: operations["get_slots_api_v1_stylists__stylist_id__slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailabilityResponse */
        AvailabilityResponse: {
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /** Rules */
            rules: components["schemas"]["AvailabilityRuleResponse"][];
        };
        /**
         * AvailabilityRuleInput
         * @description One rule. working/break need weekday + times; day_off needs only a date.
         */
        AvailabilityRuleInput: {
            kind: components["schemas"]["RuleKind"];
            /** Weekday */
            weekday?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Off Date */
            off_date?: string | null;
        };
        /** AvailabilityRuleResponse */
        AvailabilityRuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["RuleKind"];
            /** Weekday */
            weekday: number | null;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Off Date */
            off_date: string | null;
        };
        /**
         * AvailabilityUpdate
         * @description Full replacement of a stylist's rules (PUT).
         */
        AvailabilityUpdate: {
            /** Rules */
            rules: components["schemas"]["AvailabilityRuleInput"][];
        };
        /**
         * BookingCreate
         * @description The client is always the caller, so there is no client_id field.
         */
        BookingCreate: {
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** BookingResponse */
        BookingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            status: components["schemas"]["BookingStatus"];
            /** Refund Due */
            refund_due: boolean | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BookingSalonSummary
         * @description Explicit field list: no owner_id, nothing private.
         */
        BookingSalonSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Cancellation Hours */
            cancellation_hours: number;
            /** Deposit Amount */
            deposit_amount: number;
            /** Image Url */
            image_url: string | null;
        };
        /** BookingServiceSummary */
        BookingServiceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            price_type: components["schemas"]["PriceType"];
            /** Price */
            price: number | null;
        };
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "cancelled" | "completed" | "no_show";
        /**
         * BookingStylistSummary
         * @description No email or role: just what the client needs to recognise the stylist.
         */
        BookingStylistSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Image Url */
            image_url: string | null;
        };
        /**
         * ClientBookingDetailResponse
         * @description Plus the latest payment (both None until the client starts paying).
         */
        ClientBookingDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            status: components["schemas"]["BookingStatus"];
            /** Refund Due */
            refund_due: boolean | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            salon: components["schemas"]["BookingSalonSummary"];
            service: components["schemas"]["BookingServiceSummary"];
            stylist: components["schemas"]["BookingStylistSummary"];
            payment_status: components["schemas"]["PaymentStatus"] | null;
            /** Payment Amount */
            payment_amount: number | null;
        };
        /**
         * ClientBookingResponse
         * @description A booking with the salon, service and stylist summaries nested in.
         */
        ClientBookingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            status: components["schemas"]["BookingStatus"];
            /** Refund Due */
            refund_due: boolean | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            salon: components["schemas"]["BookingSalonSummary"];
            service: components["schemas"]["BookingServiceSummary"];
            stylist: components["schemas"]["BookingStylistSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OwnerBookingItem
         * @description One row of a salon owner's booking list.
         *
         *     Explicit field list on purpose: the client is shown by name only (no email, no id),
         *     and nothing from Paystack (reference, access code, checkout URL) is included.
         */
        OwnerBookingItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["BookingStatus"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Refund Due */
            refund_due: boolean | null;
            payment_status: components["schemas"]["PaymentStatus"] | null;
            stylist: components["schemas"]["OwnerBookingStylist"];
            service: components["schemas"]["OwnerBookingService"];
            /** Client Name */
            client_name: string;
        };
        /** OwnerBookingService */
        OwnerBookingService: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
        };
        /** OwnerBookingStylist */
        OwnerBookingStylist: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * PaymentResponse
         * @description What the client needs to pay. Never includes Paystack secrets or refund internals.
         */
        PaymentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            status: components["schemas"]["PaymentStatus"];
            /** Paystack Reference */
            paystack_reference: string;
            /** Authorization Url */
            authorization_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "pending" | "paid" | "refund_pending" | "refunded" | "failed";
        /**
         * PriceType
         * @enum {string}
         */
        PriceType: "fixed" | "quote";
        /**
         * PublicStylistResponse
         * @description Public view: deliberately no email or other personal fields.
         */
        PublicStylistResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Image Url */
            image_url: string | null;
            /** Service Ids */
            service_ids: string[];
        };
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "working" | "break" | "day_off";
        /** SalonCreate */
        SalonCreate: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Cancellation Hours
             * @default 24
             */
            cancellation_hours: number;
            /** Deposit Amount */
            deposit_amount: number;
        };
        /** SalonResponse */
        SalonResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Image Url */
            image_url: string | null;
            /** Cancellation Hours */
            cancellation_hours: number;
            /** Deposit Amount */
            deposit_amount: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SalonUpdate */
        SalonUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Cancellation Hours */
            cancellation_hours?: number | null;
            /** Deposit Amount */
            deposit_amount?: number | null;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            price_type: components["schemas"]["PriceType"];
            /** Price */
            price?: number | null;
        };
        /** ServiceResponse */
        ServiceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Salon Id
             * Format: uuid
             */
            salon_id: string;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            price_type: components["schemas"]["PriceType"];
            /** Price */
            price: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ServiceUpdate */
        ServiceUpdate: {
            /** Name */
            name?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            price_type?: components["schemas"]["PriceType"] | null;
            /** Price */
            price?: number | null;
        };
        /**
         * SlotsResponse
         * @description Bookable start times (salon-local, with UTC offset), earliest first.
         */
        SlotsResponse: {
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /**
             * Service Id
             * Format: uuid
             */
            service_id: string;
            /** Slots */
            slots: string[];
        };
        /** StylistCreate */
        StylistCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * StylistResponse
         * @description Owner-facing view of a stylist.
         */
        StylistResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Salon Id
             * Format: uuid
             */
            salon_id: string;
            /** Image Url */
            image_url: string | null;
        };
        /** StylistServicesResponse */
        StylistServicesResponse: {
            /**
             * Stylist Id
             * Format: uuid
             */
            stylist_id: string;
            /** Service Ids */
            service_ids: string[];
        };
        /** StylistServicesUpdate */
        StylistServicesUpdate: {
            /** Service Ids */
            service_ids: string[];
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "client" | "owner";
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_my_bookings_api_v1_bookings_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBookingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_api_v1_bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBookingDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_booking_api_v1_bookings__booking_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_api_v1_bookings__booking_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paystack_webhook_api_v1_payments_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "x-paystack-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_salons_api_v1_salons_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_salon_api_v1_salons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_salons_api_v1_salons_mine_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_salon_api_v1_salons__salon_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_salon_api_v1_salons__salon_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_api_v1_salons__salon_id__services_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_api_v1_salons__salon_id__services_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_salon_bookings_api_v1_salons__salon_id__bookings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["BookingStatus"] | null;
                stylist_id?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerBookingItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_api_v1_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_api_v1_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stylists_api_v1_salons__salon_id__stylists_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStylistResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stylist_api_v1_salons__salon_id__stylists_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                salon_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StylistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StylistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_stylist_services_api_v1_stylists__stylist_id__services_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stylist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StylistServicesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StylistServicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_api_v1_stylists__stylist_id__availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stylist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_availability_api_v1_stylists__stylist_id__availability_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stylist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slots_api_v1_stylists__stylist_id__slots_get: {
        parameters: {
            query: {
                service_id: string;
                date: string;
            };
            header?: never;
            path: {
                stylist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
